#!/bin/bash

set -e

echo "=========================================="
echo "Basic Development Tools Installation"
echo "=========================================="
echo ""
echo "Installing basic tools: curl, vim, git"
sudo apt-get update
sudo apt-get install -y curl vim git
echo ""
echo "Basic tools installed successfully!"
echo ""
echo "=========================================="
echo "Other Commonly Used Packages"
echo "=========================================="
echo ""
echo "Below is a list of other commonly used apt packages"
echo "that you may want to install based on your needs:"
echo ""
echo "  • wget"
echo "    Alternative tool for downloading files from the web"
echo "    Install with: sudo apt-get install wget"
echo ""
echo "  • build-essential"
echo "    Essential build tools (gcc, g++, make) for compiling software"
echo "    Install with: sudo apt-get install build-essential"
echo ""
echo "  • unzip"
echo "    Utility for extracting ZIP archives"
echo "    Install with: sudo apt-get install unzip"
echo ""
echo "  • ca-certificates"
echo "    Common CA certificates for SSL/TLS connections"
echo "    Install with: sudo apt-get install ca-certificates"
echo ""
echo "  • gnupg"
echo "    GNU Privacy Guard - for encryption and signing"
echo "    Install with: sudo apt-get install gnupg"
echo ""
echo "  • software-properties-common"
echo "    Tools for managing software repositories and PPAs"
echo "    Install with: sudo apt-get install software-properties-common"
echo ""
echo "  • apt-transport-https"
echo "    Allows apt to retrieve packages via HTTPS"
echo "    Install with: sudo apt-get install apt-transport-https"
echo ""
echo "=========================================="
echo ""
echo "You can install any of these packages individually,"
echo "or install multiple packages at once with:"
echo "  sudo apt-get install <package1> <package2> ..."
echo ""
