#!/bin/bash

set -e

# Base URL for downloading scripts
BASE_URL="https://oguz-kolukisa.github.io"

printf "Downloading VS Code installation script...\n"
wget -qO- "$BASE_URL/scripts/install_scripts/code.sh" | bash
